### ISSUE TITLE
Update to winston@0.4.x

### ISSUE THREAD

**Issue by indexzero** [kr1sp1n/winston-amqp#1]
Neat library!

Some useful features in the new release, specifically handling `uncaughtException` events. Main points of the refactor:
1. Inherit from `winston.Transport`
2. Emit the `logged` event when the actual logging operation is complete. This is critical. Normally you want to eagerly respond to the callback and ignore most potential errors from logs. However, in the case of logging `uncaughtExceptions` you need to be **sure** that the message has been sent before responding because you will force-exit the process.

If I'm interpreting your implementation correctly, looks like it's based on `winston-mongodb`. I've updated this library according to the above points.

**Comment by kr1sp1n** [comment]
Ok, thank you so much for your library!

I Updated my [winston-amqp](https://github.com/kr1sp1n/winston-amqp/) according to your mentioned points.
And it's already published to the npm registry ;)

Have a great day...
